/robot_news_station_giskard:
  ros__parameters:
    robot_name: giskard 
    timer_period: 1.0

/robot_news_station_bb8:
  ros__parameters:
    robot_name: bb8
    timer_period: 1.1

/robot_news_station_daneel:
  ros__parameters:
    robot_name: daneel
    timer_period: 1.2

/robot_news_station_jander:
  ros__parameters:
    robot_name: jander 
    timer_period: 1.3

/robot_news_station_c3po:
  ros__parameters:
    robot_name: c3po 
    timer_period: 1.4